### ISSUE TITLE
Search results overlap content instead of pushing it down

### ISSUE THREAD

**Issue by pantickatorce** [shishkin/astro-pagefind#101]
Hello,

I'm experiencing an issue with Pagefind where the search results are not pushing the content below them down. Instead, the results overlap with the content, making it visually unappealing and difficult to interact with.

This behavior persists even when using the default configuration and styles provided by @pagefind/default-ui/css/ui.css. I expected the search results to dynamically expand and push the following content down, but they are instead positioned underneath the existing content.

**Comment by harryk2142** [comment]
Hello, i have the same problem. Can you tell me the fix?
