### ISSUE TITLE
Feature request: query parameter

### ISSUE THREAD

**Issue by Robin-Wils** [shishkin/astro-pagefind#11]
I think it would be neat for the component to be able to use a query string. 

`/search?q=my-search-term`

**Comment by shishkin** [comment]
Hi @Robin-Wils, thanks for the idea. Do you mean that the component should access page query string directly or it should provide a prop for setting the search query?

**Comment by Robin-Wils** [comment]
Both could work. I have no preference. It makes it possible for people to link to specific searches.

**Comment by shishkin** [comment]
> It makes it possible for people to link to specific searches.

Ah, that makes perfect sense to me now. Thanks. I will look at this when I have some time.

**Comment by Robin-Wils** [comment]
I think it would be neat for 404 pages too. To lead the user to a search. I have not figured out how to read the query string in other pages either. 
https://www.robinwils.com/this-page-does-not-exist

It seems like AstroJS only allows it in SSR mode. This might be more difficult than I thought. To me it is not a must-have, but it is nice to have,. I haven't managed to fetch the URL data on my 404 page either.
- https://docs.astro.build/en/reference/api-reference/#astrorequest
- https://docs.astro.build/en/guides/server-side-rendering/#static-pre-rendering-by-default

**Comment by Robin-Wils** [comment]
The date can be fetched with the following. In server or hybrid mode. Although I have noticed that the search component does not load at all in production,  but it does locally. Maybe I am missing something, or maybe server mode is required?
```
---
export const prerender = false;
const value = Astro.url.searchParams.get("q");
---
```

**Comment by shishkin** [comment]
@Robin-Wils please check out 1.20 and let me know if it works for you. You can see [a usage example here](https://github.com/shishkin/astro-pagefind/commit/10f26d4d2efca4dbb25a2aeb81cb7b4ed13834d5#diff-e2b8913c5806f07846adec86a83dea4008cf016ca7fffd7d4e4a62b85359d398).

**Comment by Robin-Wils** [comment]
Thanks, it seems to work! I am pleased with this. Although users may not share their searches, as the query string doesn't update when typing in the input field.

I'm not sure how I can return the favor, but I appreciate the quick response.
https://www.robinwils.com/search?q=niet

**Comment by Robin-Wils** [comment]
Ah, I also found this online to focus the input field. Although I am not sure how much value it adds. It does work.
```javascript
<script>
    window.addEventListener('keydown', (event) => {
        if (event.key === '/' || event.key === '.') {
            event.preventDefault();
            document.querySelector('.pagefind-ui__search-input').focus();
        }
    });
</script>
```

**Comment by shishkin** [comment]
Yeah, that should work. I think updating the browser URL is a separate feature which I wouldn't conflate with a query parameter on the component.

You should also be able to use that event handler to update the browser URL query parameters via [History API](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState).

I'm hesitant to add URL manipulation directly into this component. Maybe adding a more convenient DOM event for search query updates would be a better alternative.

**Comment by Robin-Wils** [comment]
Hmm that does not seem great for users either, but thanks for the idea. Adding it to history every time people type a letter can make the history hard to navigate.
