### ISSUE TITLE
Could not resolve "node:path"

### ISSUE THREAD

**Issue by tobyhage** [shishkin/astro-pagefind#17]
Hello, 

Thank you for making this plugin!

After i install your package, when i run pnpm build i get the error: Could not resolve "node:path"

- I use SSR
- I use the cloudflare adapter
- when i'am running pnpm run dev everything is working

Do you know how to fix this issue? If you need more information let me know.

kind regards

**Comment by shishkin** [comment]
Hi @tobyhage, thanks raising the issue!

I can't reproduce the problem. I just tried to create a new Astro project with pnpm, added `astro-pagefind` (and `pagefind`, because pnpm apparently doesn't add transitive dependencies to `node_modules/.bin`), built and ran successfully. I'm not regularly using pnpm though and might have missed something.

The error of not being able to resolve a module prefixed with `node:` looks like something from a bundler (vite and esbuild), not package manager (pnpm). Maybe you somehow ended up having `astro-pagefind` server building code on the client call path?

Can you reproduce the problem in a sandbox like stackblitz?

**Comment by shishkin** [comment]
Please ignore my previous reply. I didn't pay attention that the problem only happens with the cloudflare adapter.

Another culprit might be cloudflare workers runtime as it also uses a bundler to build the server worker function. [Cloudflare supports](https://developers.cloudflare.com/workers/runtime-apis/nodejs/) `node:path` but may require to enable the compatibility flag. Can you try enabling it and see if it works?

**Comment by tobyhage** [comment]
Hello, 

Thank you for the reply and the suggestion.

I have followed these steps:

**Enable Node.js from the Cloudflare dashboard**
To enable Node.js for your Pages Function from the Cloudflare dashboard:

1. Log in to the Cloudflare dashboard and select your account.
2. Select Workers & Pages and in Overview, select your Pages project.
3. Select Settings > Functions > Compatibility Flags.
4. Add the nodejs_compat compatibility flag to your Preview and Production deployments.

But after a new deployment the same error occurs. Also when i build locally same error occurs. I saw that the error message i provided was very summarily. This is the more extensive error

`
✘ [ERROR] Could not resolve "node:path"

    dist/$server_build/chunks/pages/_...page_.astro.1aa274c1.mjs:1:317:
      1 │ ...ectionToGlobResultMap,h as createGetCollection}from"../astro.9e196138.mjs";import{join}from"node:path";const SiteMetadata={...
        ╵                                                                                               ~~~~~~~~~~~

  The package "node:path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

 error   Could not resolve "node:path"
  File:
    dist/$server_build/chunks/pages/_...page_.astro.1aa274c1.mjs:1:317
  Code:
    1635 |   }).join("");
    > 1636 |   let error = new Error(`${text}${summary}`);
           |               ^
      1637 |   error.errors = errors;
      1638 |   error.warnings = warnings;
      1639 |   return error;
  Stacktrace:
Error: Build failed with 1 error:
dist/$server_build/chunks/pages/_...page_.astro.1aa274c1.mjs:1:317: ERROR: Could not resolve "node:path"
    at failureErrorWithLog (/home/toby/projects/pim-astro/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1636:15)
    at /home/toby/projects/pim-astro/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1048:25
    at /home/toby/projects/pim-astro/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:993:52
    at buildResponseToResult (/home/toby/projects/pim-astro/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1046:7)
    at /home/toby/projects/pim-astro/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1075:16
    at responseCallbacks.<computed> (/home/toby/projects/pim-astro/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/home/toby/projects/pim-astro/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/home/toby/projects/pim-astro/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
`

**Comment by shishkin** [comment]
Yes, that's esbuild bundling the code and complaining about it not explicitly asked for node platform.

I just removed the call to `join` function in 43f47620c3d875f2ff29dee5d1d9fe697d4f2444. I think I can't really rely on node native modules in edge runtime adapters like cloudflare.

Please try version 1.2.1 and let me know if it works.

**Comment by tobyhage** [comment]
Thank you very much it is working now!!

I have another question/issue, i will open a new issue for this to keep thinks clear :-)
