### ISSUE TITLE
How to make search work with astro dev

### ISSUE THREAD

**Issue by louismorgan-linaro** [shishkin/astro-pagefind#20]
The integration works well when I run `astro preview` however if I run `astro dev` the search just hangs and doesn't find any results. 

I've followed the basic steps, i.e. installing the integration, adding it to config, and importing the Search component.

**Comment by kamoshi** [comment]
In recent version of this plugin [v1.2.1](https://github.com/shishkin/astro-pagefind/releases/tag/v1.2.1) the file "/_pagefind/pagefind.js" doesn't seem to be generated in `dev` mode.

Temporary workaround is to use `astro-pagefind@1.2.0`. In `package.json` pin the `1.2.0` version:
```json
{
  "dependencies": {
    "astro-pagefind": "1.2.0"
  }
}
```

**Comment by shishkin** [comment]
There was a [regression](https://github.com/shishkin/astro-pagefind/issues/19) in 1.2.1 which should have been fixed now in [1.2.2](https://github.com/shishkin/astro-pagefind/releases/tag/v1.2.2).

Also, make sure you run `astro build` at least once to build the search index before running `astro dev`.

Please let me know if you still have an issue.
