### ISSUE TITLE
Peer dependency conflict with astro 3.0

### ISSUE THREAD

**Issue by scottaw66** [shishkin/astro-pagefind#43]
npm ERR! Found: astro@3.0.7
npm ERR! node_modules/astro
npm ERR!   astro@"^3.0.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer astro@"^2.0.4" from astro-pagefind@1.2.3
npm ERR! node_modules/astro-pagefind
npm ERR!   astro-pagefind@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I was going to make a pull request to fix it, but tbh I could not figure out how to satisfy your commitlint.

**Comment by shishkin** [comment]
This should be fixed in [v1.2.4](https://github.com/shishkin/astro-pagefind/releases/tag/v1.2.4) via #47 now.
