### ISSUE TITLE
 Error: Pagefind wasn't able to build an index. 

### ISSUE THREAD

**Issue by spokospace** [shishkin/astro-pagefind#45]
Hello, what is needed to setup this Pagefind in astro project?

I added pagefind() to integration, when I run `npx pagefind --source dist` it works:
![image](https://github.com/shishkin/astro-pagefind/assets/16397823/d0cfc21e-7744-421f-9bd5-2f027c32075b)

 but when I try to build my project all the time I have this issue:

` Error: Pagefind wasn't able to build an index. Most likely, the directory passed to Pagefind was empty or did not contain any html files.`

![image](https://github.com/shishkin/astro-pagefind/assets/16397823/4d329444-2012-4e39-b2a5-a9017422f972)

**Comment by shishkin** [comment]
Thanks for reporting this. I noticed that you run on Windows and that when you run pagefind manually you specify a relative path, while the extension does put the full path in double quotes. Could you try running pagefind manually with a full path in double quotes? If that fails, it might be an issue in pagefind. I could consider passing a relative path, but that would be potentially more error-prone. Better if pagefind supports proper absolute paths on Windows.

**Comment by spokospace** [comment]
it works manually with single quotes, dobule qutes, and also without quotes. Something is wrong with integrations i think, because I can use your Search component but need to run a pagefind after build.

**Comment by shishkin** [comment]
Can you please confirm you can run `npx pagefind --source "C:\www.2023\<your_project>\dist\"` manually with a screenshot? Sorry, I don't have a Windows environment to troubleshoot that.

**Comment by meizhaohui** [comment]
If you configure a different folder as the `outDir`， you should change the config of plugin `pagefindPlugin`.

add this config :
```js
indexingCommand: 'npx pagefind --site "./dist" --output-path "pagefind" --exclude-selectors "div.aside, a.header-anchor"',
```


the reference link: [https://github.com/ATQQ/sugar-blog/blob/master/packages/vitepress-plugin-pagefind/README.md#example-6-custom-indexing-command](https://github.com/ATQQ/sugar-blog/blob/master/packages/vitepress-plugin-pagefind/README.md#example-6-custom-indexing-command)
