### ISSUE TITLE
Support showSubResults

### ISSUE THREAD

**Issue by nanaian** [shishkin/astro-pagefind#49]
I'd like to pass `showSubResults: true` to the `PagefindUI` constructor. Perhaps you could add a `uiOptions` prop to the Search component in case more options are added in future?

**Comment by shishkin** [comment]
This should be now possible in [v1.3.0](https://github.com/shishkin/astro-pagefind/releases/tag/v1.3.0). See [this example](https://github.com/shishkin/astro-pagefind/blob/7b848796e57020d0e8b13a4e6374a1e51ab5b111/packages/example/src/layouts/Main.astro#L15). Please let me know if this works for you.
