### ISSUE TITLE
Is it possible to do a single page search only?

### ISSUE THREAD

**Issue by tiwka19** [shishkin/astro-pagefind#51]
I want to do a search on blog pages only. Is that possible?

**Comment by shishkin** [comment]
Not with this project at the moment.

Pagefind [supports filters](https://pagefind.app/docs/js-api-filtering/#filtering-as-part-of-a-search) in JS API. Maybe you could add filters for blog/non-blog pages and use that. But you would need to use Pagefind JS API directly.
