### ISSUE TITLE
problem with displaying the search field

### ISSUE THREAD

**Issue by spokospace** [shishkin/astro-pagefind#55]
the search box doesn't show when you go to the next page - looks like an initialization problem - after refreshing it works ok.
Is there any way to fix this?

![image](https://github.com/shishkin/astro-pagefind/assets/16397823/ee6070ae-e11d-4256-8b0c-cff354f02f83)

after refresh the page:
![image](https://github.com/shishkin/astro-pagefind/assets/16397823/9142e4eb-61f0-4ea6-ae17-a9f0edfbe328)

**Comment by spokospace** [comment]
it seems to me it's because of I'm using the Astro Transitions (https://docs.astro.build/en/guides/view-transitions/).
There is any way to init it after changing the page with transitions?

**Comment by shishkin** [comment]
Hi @spokospace, I don't use SPA and view transitions and can't help with the issue. From the linked Astro docs I couldn't figure out what a component needs to do to properly support transitions.

**Comment by spokospace** [comment]
Hmm, maybe it's something wrong with initialization, maybe it's connected with new Astro transitions. I can confirm only, that after removing <ViewTransitions /> from layout it works okay.

**Comment by joshmedeski** [comment]
I added `astro-data-reload` to the anchor tag pointing to my "/search" page to [prevent client-side navigation](https://docs.astro.build/en/guides/view-transitions/#preventing-client-side-navigation).

Maybe that can help.

**Comment by spokospace** [comment]
I use it on search navbar in all pages, so `astro-data-reload` is not a fix for me. Idk why the pagefind input is reloaded all the time, and it need init after page load - it's different that any other vue/react component.

FYI: i fixed it by replace 
`document.addEventListener('DOMContentLoaded', () =>`
to:
`document.addEventListener('astro:page-load', () =>`

Now search input is initialized on each page with view-transitions (I have header, footer, sidebar etc. with transitions so only main cointainer is refreshed in this way)

**Comment by shishkin** [comment]
View transitions should be supported in [1.4.0](https://github.com/shishkin/astro-pagefind/releases/tag/v1.4.0) now. Please let me know if you run into further issues with them.
