### ISSUE TITLE
Astro 4 dependency

### ISSUE THREAD

**Issue by scottaw66** [shishkin/astro-pagefind#64]
Issues dependency warnings with Astro 4

**Comment by bjo3rnf** [comment]
For the time being you can install the package via GitPkg (works for me at least): 
`npm i https://gitpkg.now.sh/shishkin/astro-pagefind/packages/astro-pagefind?main`

**Comment by colinrobinsonuib** [comment]
> For the time being you can install the package via GitPkg (works for me at least): `npm i https://gitpkg.now.sh/shishkin/astro-pagefind/packages/astro-pagefind?main`

That isn't working for automated Cloudflare Pages builds

```
15:19:25.096 | npm WARN tarball tarball data for astro-pagefind@https://gitpkg.now.sh/shishkin/astro-pagefind/packages/astro-pagefind?main (sha512-JpuZVgeiK0Bj82fGmIrmjI2SBxTN9D593y7wmvCgMep562Veu+81sr6mlD6jbaAqddYUnFPah5t0krHno4aGEw==) seems to be corrupted. Trying again.
15:19:25.183 | npm ERR! code EINTEGRITY
15:19:25.185 | npm ERR! sha512-JpuZVgeiK0Bj82fGmIrmjI2SBxTN9D593y7wmvCgMep562Veu+81sr6mlD6jbaAqddYUnFPah5t0krHno4aGEw== integrity checksum failed when using sha512: wanted sha512-JpuZVgeiK0Bj82fGmIrmjI2SBxTN9D593y7wmvCgMep562Veu+81sr6mlD6jbaAqddYUnFPah5t0krHno4aGEw== but got sha512-wBO3FD8WVTRy/Q8twAA6pX6hlQNbiyiAaiFvkdVEYxS2RqNpgeS9IE0GHOBobudUPmdSkEjIzNq4E2E2dAdPew==. (3909 bytes)
```

**Comment by shishkin** [comment]
[1.4.0](https://github.com/shishkin/astro-pagefind/releases/tag/v1.4.0) is out now. Sorry for the delay.
