### ISSUE TITLE
Not work at Astro 4.0.6

### ISSUE THREAD

**Issue by yagee** [shishkin/astro-pagefind#65]
Hi! Thanks for plugin!

Add as in manual, but on dev server got this error

On local server using `astro dev` got this in browser console
![image](https://github.com/shishkin/astro-pagefind/assets/1481199/cbe067a0-e775-422d-9101-ba776a36b700)

If I try `astro build`:
![image](https://github.com/shishkin/astro-pagefind/assets/1481199/4cc0e105-b90a-4222-8d94-e902ecb8c182)

**Comment by bjo3rnf** [comment]
For the time being you can install the package via GitPkg: `npm i https://gitpkg.now.sh/shishkin/astro-pagefind/packages/astro-pagefind?main`

**Comment by yagee** [comment]
Thank you!
