### ISSUE TITLE
Update installation docs with info about `npx pagefind` command in build

### ISSUE THREAD

**Issue by mnik01** [shishkin/astro-pagefind#69]
I faced issue that my project failed in build because command `npx pagefind` falled on cloudflare CI for some reason.
Then I made `pnpm add pagefind` and it worked.

Maybe we should install it along with `astro-pagefind`? And update installation guide accordingly

**Comment by shishkin** [comment]
Hi @mnik01. I'm not using pnpm myself. Can you help me understand what needs to be done to improve pnpm users' experience with this library?

**Comment by mnik01** [comment]
Actually, I think it's not a problem with `pnpm` but maybe with Cloudflare CI 🤔
No sure. But `npx pagefind` didn't work until I installed `pagefind` as a dev Deps in project.

Then after that, `npx` was able to resolve `pagefind`.


If this situation not reproduced for any one — I guess, I can close this issue.
