### ISSUE TITLE
Pagefind only works when I run my project in dev mode.

### ISSUE THREAD

**Issue by alex-samera** [shishkin/astro-pagefind#73]
Hi there, great plugin. I am however having a strange issue.

The plugin only works when I run my project in dev mode. When I run it in preview mode or when I deploy the project to Netlify, the search box just doesn't show up. I can see the pages being successfully indexed in the deploy, but nothing shows up on the search page.

However, when I run it in dev mode everything works just fine.

Have you come across this before?

Thanks,

Alex

**Comment by shishkin** [comment]
Hi @alex-samera. This seems similar to https://github.com/shishkin/astro-pagefind/issues/71. I wonder if you use version 1.5.0 or earlier. Do you see any javascript errors in the browser console?

**Comment by alex-samera** [comment]
Hi @shishkin. Thanks for the quick response.

I'm using version 1.5.0. I have a error in the console, but I don't think it's related. I have attached it below.

![Screenshot 2024-03-22 at 09 42 45](https://github.com/shishkin/astro-pagefind/assets/56543681/f6f9ee53-eed6-4ecf-9f5b-fccbd489fb2b)

**Comment by shishkin** [comment]
Hm. It depends whether pagefind script is bundled inside that failing hoisted chunk. Any error in a script prevents further code in that scripts from executing.

**Comment by shishkin** [comment]
Cool. Glad it worked!
