### ISSUE TITLE
Doesn't work with other package managers

### ISSUE THREAD

**Issue by blueambr** [shishkin/astro-pagefind#76]
Great job on the integration 🙌

One thing I found is that due to the `npx` command inside the package, if you run `build` script with something else (not `npm`), e.g., `pnpm` — the build fails. Would be nice to have an option to use other package managers as well.

Thank you!

**Comment by onrirr** [comment]
still no fix

**Comment by jasikpark** [comment]
https://github.com/shishkin/astro-pagefind/blob/d7cf59904f824ce509aaf5301e1409abe1ff1644/packages/astro-pagefind/src/pagefind.ts#L57 

this just needs to switch to something like https://www.npmjs.com/package/detect-package-manager

**Comment by shishkin** [comment]
I removed npx call in https://github.com/shishkin/astro-pagefind/commit/5188319e7e941a901c448cb04ff395a969cdb4ca. It is released as [1.6.0](https://github.com/shishkin/astro-pagefind/releases/tag/v1.6.0)
