### ISSUE TITLE
Question - dev mode pagefind.js 404

### ISSUE THREAD

**Issue by scottaw66** [shishkin/astro-pagefind#8]
On one of my sites, astro-pagefind works beautifully in dev mode and finds the prebuilt index and the output pagefind.js in dist/_pagefind. On two of my sites, dev mode returns 404s for pagefind.js. I'm going through the sites file by file for anything that could affect this and I cannot tell the difference. Have you seen this behavior at all?

Thank you! Love this integration so much.

**Comment by scottaw66** [comment]
After doing more testing, it happens with all sites in dev mode now with current versions of astro. I'll assume something changed with astro and do some digging in the integration itself.

**Comment by shishkin** [comment]
Thanks @scottaw66 for testing and reporting! I will try to reproduce the issue with the latest dependencies (there were unreleased updates from renovate bot).

**Comment by shishkin** [comment]
@scottaw66 yes, this is a [regression in astro](https://github.com/withastro/astro/issues/6729#issuecomment-1500245158) (or potentially vite).

**Comment by scottaw66** [comment]
Ben fixed this in Astro 2.2.1

[https://github.com/withastro/astro/blob/refs/heads/main/packages/astro/CHANGELOG.md#221](https://github.com/withastro/astro/blob/refs/heads/main/packages/astro/CHANGELOG.md#221)

**Comment by shishkin** [comment]
@casimcdaniels can you ensure you have updated Astro to at least 2.2.1 along with updating astro-pagefind? If you have a reproduction somewhere I can have a look.

**Comment by casimcdaniels** [comment]
@shishkin Ah, I see. I was thinking this plugin ran on update in the dev server, so I didn't realize I needed to first do a production build against it.
