### ISSUE TITLE
Special symbols

### ISSUE THREAD

**Issue by HuangYiming0608** [shishkin/astro-pagefind#85]
> In my [website](https://huangyiming0608.github.io/)(In Chinese), I use some special symbols, such as `C++`. If my search key word is `C++`, there is nothing! But If I use `C`, I can find this page.

Is it because of special symbols?

**Comment by shishkin** [comment]
This wrapper library doesn't handle user input nor user content. Please report to [Pagefind](https://github.com/CloudCannon/pagefind) instead.
