### ISSUE TITLE
Are there any plans to support pnpm?

### ISSUE THREAD

**Issue by zachczx** [shishkin/astro-pagefind#86]
Thanks for this project! Just thought to ask if there are plans to support pnpm? 

The npx command caused an error when I tried to switch to pnpm. Seems like pnpm requires the use of "pnpm dlx" instead and it feels like it'd be a minor change. 

(Edited, fixed error, I meant dlx)

**Comment by shishkin** [comment]
I removed npx call in 5188319e7e941a901c448cb04ff395a969cdb4ca. It is released as [1.6.0](https://github.com/shishkin/astro-pagefind/releases/tag/v1.6.0)

**Comment by zachczx** [comment]
Thanks, much appreciated!!
