### ISSUE TITLE
Use processResult in uiOptions?

### ISSUE THREAD

**Issue by paulrudy** [shishkin/astro-pagefind#94]
I'm trying to add PageFind's [`processResult`](https://pagefind.app/docs/ui/#process-result)  UI config option, but it doesn't seem to work. Silly example changing all results and subresults to 'https://kagi.com':

```
<Search
  id="search"
  className="pagefind-ui"
  uiOptions={{
    showImages: false,
    showSubResults: true,
    processResult: (result) => {
      result.url = 'https://kagi.com';
      result.sub_results = result.sub_results.map((sub_result) => {
        sub_result.url = 'https://kagi.com';
        return sub_result;
      });
    },
  }}
/>
```
This doesn't work: no urls are changed.

My use case is to borrow this [snippet](https://github.com/withastro/starlight/blob/46d53aa2ac6a25e25159b4294b63d1824c3253c1/packages/starlight/components/Search.astro#L148-L154) from Astro Starlight to remove trailing slashes from results.

**Comment by shishkin** [comment]
That is expected because `uiOptions` are [JSON-serialized](https://github.com/shishkin/astro-pagefind/blob/c814c27aec37223f9894a9c6fd350ff8c33cb5fe/packages/astro-pagefind/src/components/Search.astro#L21). This is a standard limitation of Astro components and a [recommended way](https://docs.astro.build/en/guides/client-side-scripts/#pass-frontmatter-variables-to-scripts) to pass props in Astro.

Starlight example works because they use the PagafindUI directly in their client script, bypassing Astro component rendering.

I guess one way to solve for this would be to dispatch a custom DOM event that client handler could add its own callback to. But at the moment I would say you're better of just instantiating PagefindUI yourself in your client script.

**Comment by paulrudy** [comment]
Okay, that makes sense. Thanks for the explanation!

**Comment by paulrudy** [comment]
> I guess one way to solve for this would be to dispatch a custom DOM event that client handler could add its own callback to. But at the moment I would say you're better of just instantiating PagefindUI yourself in your client script.

@shishkin By the way, if for whatever reason you decide to add the dispatch of a custom DOM event to this integration, I'll be following! It's a minor annoyance that Pagefind adds trailing slashes, but I'd prefer to use your excellent integration. And I don't think I can instantiate PagefindUI myself while still using astro-pagefind, can I?

**Comment by shishkin** [comment]
@paulrudy This integration consists of two parts: the [vite plugin](https://github.com/shishkin/astro-pagefind/blob/c814c27aec37223f9894a9c6fd350ff8c33cb5fe/packages/astro-pagefind/src/pagefind.ts) that builds pagefind index and the [Astro component](https://github.com/shishkin/astro-pagefind/blob/c814c27aec37223f9894a9c6fd350ff8c33cb5fe/packages/astro-pagefind/src/components/Search.astro) that renders PagefindUI. You can totally use one without the other. Just look at the source and borrow what you need.

Also, you might want to check out Astro `build.format` [config option](https://docs.astro.build/en/reference/configuration-reference/#buildformat) if you want to change URLs from `/page/` to /page.html`.

**Comment by paulrudy** [comment]
@shishkin Thanks for explaining, I understand how this integration works now! And I appreciate the suggestion of using `build.format`, but my preference is to have cleaner-looking URLs (_without_ `.html` and _without_ a trailing slash, so that they match my page routes).

In case you might think it would be useful to others, I've created a PR #95 that adds an optional prop to strip trailing slashes, using code based on code from Starlight's [Search component](https://github.com/withastro/starlight/blob/46d53aa2ac6a25e25159b4294b63d1824c3253c1/packages/starlight/components/Search.astro#L148).
